language: java

jdk:
  - oraclejdk8

env:
  global:
  - secure: aBmO/2GTkXvK4DzomUvV72WxLFNtDLoI/qB/2MJAjgAqcuqY2pW5bOJ+WzrWQ6/zrN5QeZpWJoFzdEym/Q3s0sJ5AUS/cIgRKra/OHaFp59Z1VpVMc/6rdBuCy53ICfpmEH7ERu1HeBk/h1u1O4QvxIzbprlcRBG5raTfp/YIJO32yoDyLSr6nd/hwN/DTmg7qahlGcctnJhvzTfn5uRDXqrFZyPV7Rp410u0BfQdkqOf7+/zqRjnh8qhXuigV5pqxKcUSXZ81EQksFO582haJ7eNunOooAcfLQms6Za8CiMe5zk0jIhESjPay68islbuzMeiyyL/cz/TBzO5JWNUsq4a5Z4in8hOHGbQziThNEY5o6/mUT1rFG6UMTMS8CRV4RuvMeFZ91XKnDOQlVcAgT1ZFrMgZgNUjpgabiCJi7S4nO97pi/XJmTWSlK+xUzBpLRhFpeaAuPTP1b/iPUf/2bipGJdyqoQuNDfdd6xJolMKLjOm9kV1JWybLaHT2mwRbmsEDbGZNEW2GEzzR0l9RCoYihjk7tPQtdNImIXaSD/Sl2XxLh3kXjJg+cGiu/Em1ytWbZLWklwvMNRl5/OokkYxqEYtLr358xYPn+F7qkiBfsvtJN/Uc15NJ4YkmHniWYWkuw6Mb61lcVXj4q+rR6QHXSRcdPbd3pRM4OtYs=
  - secure: b1OJRbopXUbKsi8SC0NHIdQrX/X3vipcDhfbACjeM0OCTTRX3IzOpbntFTJQmqDW2GhTQz3Ftz06PejJ8RmA3tfGJpFodio+a66ooHUaCWvdjPLDPRgGZYy6hTzUzI/lBMhqhPZCZfb6KVgGHStrI0VEqKzCzqAdVeXKaxpPlWW2C7sSA54Yvytkz2R4I21Z9YC1GIkqCGSrr9oOtQ2Ri7Zi2ZEjW9+YydbwCFxinzUnWvNwJWP5IrK3M4xLa2L53UQh6ahHEac2S6q1EGEIdigtcB/EXmLXr2lsSvOddfCdSF6ZOlUYwKs2ObO++/3rHdcrhUhpe5FPfc9kcvQ3cR32AFye6HD5C8Q0PvGd22o+WgcsO3RpTLS5qdYWKGKgoLnozgxNy+W7DU+4l+Qkr1fjWnETEGrVwch4oOHP5FbgY14ygPetjLz8h1bXRP0BP8A1ZXQweOEO4XwGFJ5oo8zxZ4vxFy6PEnxD61+2wv/F9M+0wJc2s4Gm0i2K0ODCEu6/x5RlDbjmsNgoXCpAgd3j8qxajoY0QlqaXwFjm48MfGEs3/Z0MwaVwnagkAQjwFPWHxCgOac07wToYzSvUbDPy7Z0JUbthV6wriJx3ljQvpH7YE0qa+JByu+hvvMNMeCJtsJLcvQtkb22QW5wuh7Wh2csgqL4A6/Z+LccVu0=
  - secure: Cg4NiHrU/Hqklc4tmpz+Ohuea1ggv/lv0SpzQEmkjC6Fm6UqFB4xsA++QRJUOlCWxPoVWooeorThD+wkQxxYtwCfpDhu9L5DmVuVK2qYPqYNpgBaNxQPQ6onu8e1NTN47A3OW1y0w8yOoDrM07EyiheXLeasDkXxvwI6L49SSOFCTQmQaBjdDpgm/AuF0EThu9INXlx3CSdWN6ozCnkMX6fnQNBwGcrcuAQpUNHDRFDWqQZwvKaTUvGJOrhR4KJLoa2JToFlPalg9bpnR8lXSVbojrbaT6twS5dIJyU/x4yA+KcRGyVQGjTEW8/jNZYGUnn2BLoyx/Cl0uKgukGK/QjFIz5hh/Kts13zoQWf/L7YeK4CkxLQ7p3dStprc5G4AYzUgPBTKlyOwGnHkmcG2m4XltXbHjlB/j4ncnprb+pQllXYR/V1n7Ns+nClNxcjiD6OXYCiYJhIe2U6+KdsTn6ukZZomtzOIv4Ys93lPL2sPvtYlNlZRyoqHKG5P6rHPHWDY8uVa8cR6kYMY9tfo9jJluIC8nrjxkeSwp4CFHllf6LNy8HiEayHsfWKhLICit9hjYutthS91kr3T6iJEJL+4iZpPswLgEqQvYePgrIGHz3UOLJu+nX3EbY8N2uUCCEBfM+TMOH497Hu/KO7pJoF19xA/tUS+C7OQicPcLM=
  - secure: kXasvy8piuT23IcNTLgEKpu8TPfyPBLI05GwHwP1PYU6sF/tzgCYzvBWyvkD3phI+vfMuC4+/dQsaa4ZlbIdJtdRNurxNgeKJ6y7pAlOtBrL6EUT1mkOhtmGEvjpFYM6lD2bATARGh+1RA5SjULjk7XBhZFOceaH+ccAgBkDgVKwzEBdKsfv+2Zv7Yh5SFx/Xlqbi3+BAmoueRxpqDBniVREu/rsw5HvRNt2qG38cFVzst420XifOrEStTsaguGQPJ/actfM7HD68AS/BChQZTxY2J5VebSU+Y6zSM8bR3qsjYrvSTd5yaaos4m3CbdYpzEg1JxrFXGA0EofN1ARKS/S1HT4aTd3qjgbLMNy2raDVzh/31O2MjjDPfz1kDK2II8fEH+ZZ36eCWXl/QncpabzAF5BgooPSVJO6oqUf87hjEQzb+otS/NY8KPoVd3pXQEPA8lMaQ+QnexXBsJjYyyNOP98ZzGXSOQTkCi/CmWBvm1f+OY1ZkywwJj/qjKdBts8iXEa+uoHT4B67fsGBIMfaYoaCVSglqEMTFID9ydzr7i6JInDjZzRbMHmK6dceNKglsWppDbJE7soXksPHK6LoZy1+smmPUqEVLoDzmrKFv1WbsGHnGSMrfkdyI+jVGIzxc9AJ9Nt3ksvw2CscicGiQKW86e0Y58rroIXZMo=

os:
  - linux

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
  branch:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

before_script:
- ./gradlew clean
- mkdir build build/classes build/classes/test
- cp -r src/test/java/resources build/classes/test/resources

script:
- ./gradlew test && ./gradlew jar

after_success:
- ./gradlew jacocoTestReport coveralls
- .utility/initiate-publish.sh